// <auto-generated />
namespace LapTrinhQuanLi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class create_tbla : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_tbla));
        
        string IMigrationMetadata.Id
        {
            get { return "202203141410414_create_tbl a"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
